export const mockCards = [
  {
    id: "1",
    name: "Mixmax",
    budget_name: "Software subscription",
    owner_id: "123",
    spent: { value: 1000 },
    available_to_spend: { value: 0 },
    card_type: "burner",
    expiry: "2026-02-09",
    status: "active",
  },
  {
    id: "2",
    name: "Netflix",
    budget_name: "Entertainment",
    owner_id: "456",
    spent: { value: 50 },
    available_to_spend: { value: 100 },
    card_type: "subscription",
    limit: 200,
    status: "active",
  },
  {
    id: "3",
    name: "Google Ads",
    budget_name: "Marketing",
    owner_id: "123",
    spent: { value: 300 },
    available_to_spend: { value: 50 },
    card_type: "burner",
    expiry: "2026-03-01",
    status: "blocked",
  },
];
