export const mockCards = [
  {
    id: "1",
    name: "Mixmax",
    budget_name: "Software subscription",
    owner_id: "123",
    spent: { value: 1000, currency: "SGD" },
    available_to_spend: { value: 0, currency: "SGD" },
    card_type: "burner",
    expiry: "2026-02-09",
    status: "active",
  },
  {
    id: "2",
    name: "Netflix",
    budget_name: "Entertainment",
    owner_id: "456",
    spent: { value: 50, currency: "SGD" },
    available_to_spend: { value: 100, currency: "SGD" },
    card_type: "subscription",
    limit: 200,
    status: "active",
  },
  {
    id: "3",
    name: "Google Ads",
    budget_name: "Marketing",
    owner_id: "123",
    spent: { value: 300, currency: "SGD" },
    available_to_spend: { value: 50, currency: "SGD" },
    card_type: "burner",
    expiry: "2026-03-01",
    status: "blocked",
  },
  {
    id: "4",
    name: "Slack",
    budget_name: "Team Tools",
    owner_id: "123",
    spent: { value: 80, currency: "SGD" },
    available_to_spend: { value: 420, currency: "SGD" },
    card_type: "subscription",
    limit: 500,
    status: "active",
  },
  {
    id: "5",
    name: "AWS",
    budget_name: "Cloud",
    owner_id: "456",
    spent: { value: 600, currency: "SGD" },
    available_to_spend: { value: 400, currency: "SGD" },
    card_type: "burner",
    expiry: "2026-04-01",
    status: "active",
  },
  {
    id: "6",
    name: "Zoom",
    budget_name: "Video Calls",
    owner_id: "123",
    spent: { value: 15, currency: "SGD" },
    available_to_spend: { value: 35, currency: "SGD" },
    card_type: "subscription",
    limit: 50,
    status: "active",
  },
  {
    id: "7",
    name: "GitHub",
    budget_name: "Dev Tools",
    owner_id: "123",
    spent: { value: 20, currency: "SGD" },
    available_to_spend: { value: 0, currency: "SGD" },
    card_type: "subscription",
    limit: 20,
    status: "active",
  },
  {
    id: "8",
    name: "Figma",
    budget_name: "Design Tools",
    owner_id: "456",
    spent: { value: 45, currency: "SGD" },
    available_to_spend: { value: 105, currency: "SGD" },
    card_type: "subscription",
    limit: 150,
    status: "active",
  },
  {
    id: "9",
    name: "Adobe",
    budget_name: "Creative Cloud",
    owner_id: "123",
    spent: { value: 55, currency: "SGD" },
    available_to_spend: { value: 0, currency: "SGD" },
    card_type: "subscription",
    limit: 55,
    status: "active",
  },
  {
    id: "10",
    name: "LinkedIn Ads",
    budget_name: "Marketing",
    owner_id: "456",
    spent: { value: 200, currency: "SGD" },
    available_to_spend: { value: 800, currency: "SGD" },
    card_type: "burner",
    expiry: "2026-05-15",
    status: "active",
  },
  {
    id: "11",
    name: "Spotify",
    budget_name: "Music",
    owner_id: "123",
    spent: { value: 10, currency: "SGD" },
    available_to_spend: { value: 10, currency: "SGD" },
    card_type: "subscription",
    limit: 20,
    status: "active",
  },
  {
    id: "12",
    name: "Vercel",
    budget_name: "Hosting",
    owner_id: "456",
    spent: { value: 40, currency: "SGD" },
    available_to_spend: { value: 60, currency: "SGD" },
    card_type: "subscription",
    limit: 100,
    status: "active",
  },
  {
    id: "13",
    name: "ChatGPT Plus",
    budget_name: "AI Tools",
    owner_id: "123",
    spent: { value: 20, currency: "SGD" },
    available_to_spend: { value: 0, currency: "SGD" },
    card_type: "subscription",
    limit: 20,
    status: "active",
  },
  {
    id: "14",
    name: "Mailchimp",
    budget_name: "Email Marketing",
    owner_id: "456",
    spent: { value: 150, currency: "SGD" },
    available_to_spend: { value: 150, currency: "SGD" },
    card_type: "burner",
    expiry: "2026-06-20",
    status: "blocked",
  },
  {
    id: "15",
    name: "DigitalOcean",
    budget_name: "Cloud Hosting",
    owner_id: "123",
    spent: { value: 90, currency: "SGD" },
    available_to_spend: { value: 110, currency: "SGD" },
    card_type: "subscription",
    limit: 200,
    status: "active",
  },
  {
    id: "16",
    name: "Canva",
    budget_name: "Marketing",
    owner_id: "456",
    spent: { value: 12, currency: "SGD" },
    available_to_spend: { value: 38, currency: "SGD" },
    card_type: "subscription",
    limit: 50,
    status: "active",
  },
  {
    id: "17",
    name: "Jira",
    budget_name: "Project Management",
    owner_id: "123",
    spent: { value: 100, currency: "SGD" },
    available_to_spend: { value: 400, currency: "SGD" },
    card_type: "subscription",
    limit: 500,
    status: "active",
  },
  {
    id: "18",
    name: "Cloudflare",
    budget_name: "Security",
    owner_id: "456",
    spent: { value: 200, currency: "SGD" },
    available_to_spend: { value: 300, currency: "SGD" },
    card_type: "burner",
    expiry: "2026-07-10",
    status: "active",
  },
  {
    id: "19",
    name: "Intercom",
    budget_name: "Customer Support",
    owner_id: "123",
    spent: { value: 500, currency: "SGD" },
    available_to_spend: { value: 0, currency: "SGD" },
    card_type: "burner",
    expiry: "2026-01-01",
    status: "blocked",
  },
  {
    id: "20",
    name: "Notion",
    budget_name: "Documentation",
    owner_id: "456",
    spent: { value: 48, currency: "SGD" },
    available_to_spend: { value: 52, currency: "SGD" },
    card_type: "subscription",
    limit: 100,
    status: "active",
  },
];
